// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbO_jANYQYN7jfhKhYTae4vu3e0PfeNQU',
    appId: '1:265157656052:web:9f4ed9ecb7b2e723b18da1',
    messagingSenderId: '265157656052',
    projectId: 'spendwise-c3116',
    authDomain: 'spendwise-c3116.firebaseapp.com',
    storageBucket: 'spendwise-c3116.firebasestorage.app',
    measurementId: 'G-N2PJCK3Y0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1F-8jBfaF-kvkEjyUgfOXTbHtpzgDcaw',
    appId: '1:265157656052:android:6bfe547e67c1083eb18da1',
    messagingSenderId: '265157656052',
    projectId: 'spendwise-c3116',
    storageBucket: 'spendwise-c3116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGra2JsTs7tF2crHn041hMo_thrkmO5uw',
    appId: '1:265157656052:ios:10fccb1e9362592fb18da1',
    messagingSenderId: '265157656052',
    projectId: 'spendwise-c3116',
    storageBucket: 'spendwise-c3116.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGra2JsTs7tF2crHn041hMo_thrkmO5uw',
    appId: '1:265157656052:ios:10fccb1e9362592fb18da1',
    messagingSenderId: '265157656052',
    projectId: 'spendwise-c3116',
    storageBucket: 'spendwise-c3116.firebasestorage.app',
    iosBundleId: 'com.example.spendwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbO_jANYQYN7jfhKhYTae4vu3e0PfeNQU',
    appId: '1:265157656052:web:119cbabb349f925cb18da1',
    messagingSenderId: '265157656052',
    projectId: 'spendwise-c3116',
    authDomain: 'spendwise-c3116.firebaseapp.com',
    storageBucket: 'spendwise-c3116.firebasestorage.app',
    measurementId: 'G-WKNBE5MDKV',
  );
}
